openapi: 3.0.1
info:
  title: OpenAPI for R
  version: '1.0'
servers:
- url: /v1
tags:
- name: g1
  description: Group 1 analytics 
paths:
  /incr:
    get:
      tags:
      - g1
      description: Increment an integer number
      parameters:
        - name: "n"
          description: "integer number to increment"
          in: query
          schema:
            type: integer
          example: 10
          required: true
      responses:
        200:
          description: API response
          content:
            text/plain:
              schema:
                type: string
                example: 5
        400:
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: cat
