openapi: 3.0.1
info:
  title: OpenAPI for Python
  version: "1.0"
servers:
- url: /v1
tags:
- name: g1
  description: Group 1 analytics
paths:
  /incr:
    get:
      tags:
      - g1
      description: Increment an integer number
      operationId: incr_get
      parameters:
      - name: "n"
        in: query
        description: integer number to increment
        required: true
        style: form
        explode: true
        schema:
          type: integer
        example: 10
      responses:
        "200":
          description: API response
          content:
            text/plain:
              schema:
                type: string
                example: "11"
                x-content-type: text/plain
      x-openapi-router-controller: swagger_server.controllers.g1_controller
components: {}

